Iter13
dolgalevd/urlShortener pull request #18
Opened 2024-05-14 15:11 UTC by dolgalevd

2024-05-15 10:12 UTC, gonozov0 requested changes
Отличная работа 👍
Довольно легко было погружаться в код
Оставил пару комментариев по улучшению

2024-05-15 10:12 UTC, gonozov0 commented on internal/handlers/handlers.go
> +			w.Write(resp)
аналогично

2024-05-15 10:12 UTC, gonozov0 commented on internal/storage/postgres.go
> +	//`INSERT INTO links(correlation_id, origin_url, shorted_url) VALUES ($1, $2, $3);`,
забыл удалить коммент

2024-05-20 13:10 UTC, dolgalevd commented on internal/handlers/handlers.go
> +		if serr, ok := err.(*storage.OriginalURLAlreadyExistError); ok {
Почему именно is. Как я понимаю is используется для сравнения по значению
As для сравнения по типу.

Так как ошибка содержит дополнительное поле, то проверять по значению не корректно же в данном случае

2024-05-21 07:58 UTC, gonozov0 commented on internal/handlers/handlers.go
> +		if serr, ok := err.(*storage.OriginalURLAlreadyExistError); ok {
Да, ты прав, в твоем кейсе действительно нужно использовать errors.As

2024-05-21 07:58 UTC, gonozov0 approved these changes
Все моменты поправлены 💪

2024-05-27 23:11 UTC, merged